spring:
    application:
        name: esercizio-unit-test

---
environment: test
spring:
    datasource:
        url: jdbc:h2:mem:testunittest
        username: Ttamer
        password: test
        driver-class-name: org.h2.Driver
    jpa:
        database: h2
    h2:
        console:
            enabled: true

